# serverless.yml

service: fruit-project-api-scraper
frameworkVersion: '3'

plugins:
  - serverless-prune-plugin

params:
  default:
    table1: 'fruit'
    table2: 'cocktail-recipes'
    table3: 'food-recipes'
    app: 'fruit-project-api-scraper'

provider:
  name: aws
  runtime: python3.10
  ecr:
    images:
      fruit-project-api-scraper:
        path: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${param:app}:latest
  region: eu-west-2
  runtimeManagement: auto
  memorySize: 512
  timeout: 10
  environment:
    APP: ${param:app}
    SOURCE_API_NAME: "fruity-vice"

  iam:
    role:
      name: ${param:app}-lambda-role
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table1}
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table2}
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table3}

functions:
  fruit-project-api-scraper:
    image: fruit-project-api-scraper

custom:
  prune:
    automatic: true
    number: 3