	
# serverless.yml
 
service: fruit-project-api-scraper
frameworkVersion: '3'

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
 


params:
  default:
    table1: 'fruit'
    table2: 'cocktail-recipes'
    table3: 'food-recipes'

provider:
  name: aws
  runtime: python3.10
  region: eu-west-2
  runtimeManagement: auto
  memorySize: 512
  timeout: 10
  environment:
    APP: "fruit-project-api-scraper"
    SOURCE_API_NAME: "fruity-vice"
  logRetentionInDays: 14  	
  lambdaHashingVersion: 20201221

  iam:
    role:
      name: fruit-project-api-scraper-lambda-role
      statements:
        - Effect: "Allow"
          Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Resource: 
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table1}
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table2}
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:${param:table3}
 
functions:
  fruit-project-api-scraper:
    handler: handler.main
    package:
      exclude:
      - node_modules/**
      - .idea/**
      - .requirements/**
      - env/**
      - README.md
      - package.json
      - package-lock.json
      - requirements.txt

custom:
  pythonRequirements:
    zip: true
    # pythonBin: /opt/python3.10/bin/python
  prune:
    automatic: true
    number: 3

