service: fruit-project-api-scraper
frameworkVersion: '4'

plugins:
  - serverless-prune-plugin
  - serverless-step-functions

params:
  default:
    table1: 'fruit'
    table2: 'cocktail-recipes'
    table3: 'food-recipes'
    targetApi1: 'fruity-vice'
    targetApi2: 'the-cocktail-db'
    targetApi3: 'the-meal-db'
    functionName: '${self:service}-${sls:stage}'
    dynamoDbArnPrefix: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table"
    lambdaArnPrefix: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function'
     
provider:
  name: aws
  ecr:
    images:
      appImage:
        uri: ${param:imageURI}
  region: eu-west-2
  runtimeManagement: auto
  memorySize: 512
  timeout: 10

functions:
  app:
    name: ${param:functionName}
    image: appImage

stepFunctions:
  stateMachines:
    projectStateMachine:
      name: ${self:service}-state-machine-${sls:stage}
      definition:
        Comment: "State Machine to chain executions of fruit-project-api-scraper for ${sls:stage}"
        StartAt: FruitTableUpdate
        States:
          FruitTableUpdate:
            Next: CocktailTableUpdate
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: $.errorInfo
              Next: ScrapingFailed
            Parameters:
              FunctionName: ${param:lambdaArnPrefix}:${param:functionName}
              Payload:
                app: ${self:service}
                sourceApiName: ${param:targetApi1}
          CocktailTableUpdate:
            Next: FoodTableUpdate
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Catch:
            - ErrorEquals: ["States.ALL"]
              ResultPath: $.errorInfo
              Next: ScrapingFailed
            Parameters:
              FunctionName: ${param:lambdaArnPrefix}:${param:functionName}
              Payload:
                app: ${self:service}
                sourceApiName: ${param:targetApi2}
          FoodTableUpdate:
            Next: ScrapingSucessful
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Catch:
            - ErrorEquals: ["States.ALL"] 
              ResultPath: $.errorInfo
              Next: ScrapingFailed
            Parameters:
              FunctionName: ${param:lambdaArnPrefix}:${param:functionName}
              Payload:
                app: ${self:service}
                sourceApiName: ${param:targetApi3}
          ScrapingFailed:
            Type: Fail
            Cause: "Scraping process failed"
            Error: "Error Encountered during scraping"
          ScrapingSucessful:
            Type: Pass
            Result: "All target apis scraped"
            End: true

custom:
  prune:
    automatic: true
    number: 3
