import simplejson as json

fruity_vice_api_records = [
    {
        "name": "Persimmon",
        "id": 52,
        "family": "Ebenaceae",
        "order": "Rosales",
        "genus": "Diospyros",
        "nutritions": {
            "calories": 81,
            "fat": 0.0,
            "sugar": 18.0,
            "carbohydrates": 18.0,
            "protein": 0.0,
        },
    },
    {
        "name": "Strawberry",
        "id": 3,
        "family": "Rosaceae",
        "order": "Rosales",
        "genus": "Fragaria",
        "nutritions": {
            "calories": 29,
            "fat": 0.4,
            "sugar": 5.4,
            "carbohydrates": 5.5,
            "protein": 0.8,
        },
    }]

fruity_vice_api_records_with_dropped_fields_not_needed = [
    {
        "name": "Persimmon",
        "id": 52,
        "family": "Ebenaceae",
        "order": "Rosales",
        "genus": "Diospyros",
    },
    {
        "name": "Strawberry",
        "id": 3,
        "family": "Rosaceae",
        "order": "Rosales",
        "genus": "Fragaria",

    }]

cocktail_db_api_records = '''
{ "drinks" : [
    {
        "idDrink": "178371",
        "strDrink": "Old Cuban",
        "strDrinkAlternate": null,
        "strTags": null,
        "strVideo": null,
        "strCategory": "Cocktail",
        "strIBA": null,
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake a handful of mint, 2oz white rum, ...",
        "strInstructionsES": null,
        "strInstructionsDE": null,
        "strInstructionsFR": null,
        "strInstructionsIT": null,
        "strInstructionsZH-HANS": null,
        "strInstructionsZH-HANT": null,
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/eo8gfx1699022995.jpg",
        "strIngredient1": "White Rum",
        "strIngredient2": "Sugar Syrup",
        "strIngredient3": "Lime Juice",
        "strIngredient4": "Angostura Bitters",
        "strIngredient5": "Prosecco",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": null,
        "strIngredient9": null,
        "strIngredient10": null,
        "strIngredient11": null,
        "strIngredient12": null,
        "strIngredient13": null,
        "strIngredient14": null,
        "strIngredient15": null,
        "strMeasure1": "2 oz",
        "strMeasure2": "1 oz",
        "strMeasure3": "1 oz",
        "strMeasure4": "2 dashes",
        "strMeasure5": "2 oz",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": null,
        "strMeasure9": null,
        "strMeasure10": null,
        "strMeasure11": null,
        "strMeasure12": null,
        "strMeasure13": null,
        "strMeasure14": null,
        "strMeasure15": null,
        "strImageSource": "Instagram",
        "strImageAttribution": null,
        "strCreativeCommonsConfirmed": "No",
        "dateModified": null
    },
    {
        "idDrink": "178370",
        "strDrink": "Mauresque",
        "strDrinkAlternate": null,
        "strTags": null,
        "strVideo": null,
        "strCategory": "Cocktail",
        "strIBA": null,
        "strAlcoholic": "Alcoholic",
        "strGlass": "Collins glass",
        "strInstructions": "1 - Pour the Ricard (or pastis)\\r\\n2 ...",
        "strInstructionsES": null,
        "strInstructionsDE": null,
        "strInstructionsFR": null,
        "strInstructionsIT": null,
        "strInstructionsZH-HANS": null,
        "strInstructionsZH-HANT": null,
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/duwfa11686236556.jpg",
        "strIngredient1": "Ricard",
        "strIngredient2": "Orgeat Syrup",
        "strIngredient3": "Water",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": null,
        "strIngredient9": null,
        "strIngredient10": null,
        "strIngredient11": null,
        "strIngredient12": null,
        "strIngredient13": null,
        "strIngredient14": null,
        "strIngredient15": null,
        "strMeasure1": "3 cl",
        "strMeasure2": "1 cl",
        "strMeasure3": "Full Glass",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": null,
        "strMeasure9": null,
        "strMeasure10": null,
        "strMeasure11": null,
        "strMeasure12": null,
        "strMeasure13": null,
        "strMeasure14": null,
        "strMeasure15": null,
        "strImageSource": "https://thecocktailist.fr/wp-content/uploads/2022/06/kitscocktails-mauresquedeluxe-1065.jpg",
        "strImageAttribution": null,
        "strCreativeCommonsConfirmed": "No",
        "dateModified": null
    }
]}
'''

sample_api_response_dicts = { "fruity-vice" : fruity_vice_api_records,
                             "fruity-vice-with-dropped-fields-not-needed" : fruity_vice_api_records_with_dropped_fields_not_needed,
                              "the-cocktail-db" : json.loads(cocktail_db_api_records)}
