on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      test_file:
        type: string
        required: true

jobs:
  pytest:
    name: Pytest Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_call.head_sha }}
        repository: ${{ github.repository }}
    - name: 'hello world'
      run: | 
        echo 'hello world'
        echo "Python version"
        echo ${{ vars.PYTHON_VERSION }}
        echo "Python test dir"
        echo ${{ vars.PYTEST_TEST_DIR }}
        echo 'checked out'
        echo "test_file"
        echo ${{ inputs.test_file }}
        ls -la
    # - name: Set up Python version - ${{ vars.PYTHON_VERSION }}
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ vars.PYTHON_VERSION }}
    # - name: Install dependencies  
    #   run: |  
    #       python -m pip install --upgrade pip  
    #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Test with pytest
    #   run: pytest -vv ${{ vars.PYTEST_TEST_DIR }}/test_${{ inputs.test_file }}.py
