on:
  pull_request:
    branches:
      - main
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: feature
  cancel-in-progress: true

jobs:
  pytest:
    name: Pytest
    permissions:
      contents: read
    strategy:  
      matrix:  
        test_file: ${{ fromJson('["api_mapping_manager", "record_manager", "scraper", "utils"]') }}
    uses: KremzeeqOrg/gha-reusable-workflows/.github/workflows/pytest-unit-test-workflow.yml@main
    with:
      environment: feature
  serverless-deploy:
    name: Serverless Deploy
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/serverless-deploy-workflow.yml
    with:
      environment: feature


