on:
  pull_request:
    branches:
      - closed
    types: [labeled]

env:
  TEST_DIR: "src/tests"
  PYTHON_VERSION: '3.10'
  NODE_VERSION: 20
  AWS_REGION: "eu-west-2"
  APP: "fruit-project-api-scraper"
  ENV: dev

jobs:
  teardown:
    permissions:
      id-token: write
      contents: read
    name: "Serverless Remove"
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'deploy' }} || ${{ github.event.action == 'closed' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set AWS context
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: true
    - name: serverless teardown
      run: | 
        npm i -g serverless@3.38.0
        serverless remove --verbose --stage dev
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}