on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'src/*'
      - '.github/workflows/serverless-workflow.yml'

jobs:
  pytest:
    name: "Pytests"
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        test_file: ["api_mapping_manager", "record_manager", "scraper", "utils"]
    env:
      TEST_DIR: "src/tests"
      PYTHON_VERSION: 3.11
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python version - ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies  
      run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Lint with Ruff  
      run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 .  
      continue-on-error: true
    - name: Test with pytest
      run: pytest -vv ${{ env.TEST_DIR }}/test_${{ matrix.test_file }}.py
